image: timbru31/node-alpine-git

pipelines:
  default:
    - step:
        name: Build

        script:
          - export BUILD_VERSION="$APP_VERSION.$(git rev-parse --short=8 HEAD)"
          - "echo Version: $BUILD_VERSION"
          - mkdir build
          - cd build
          - npm pack ..
          - mv *.tgz ugcs-web-dxf-viewer.$BUILD_VERSION.tgz
          - cd ..
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "eu-west-1"
              S3_BUCKET: "ugcs-build-artifacts/ugcs-web-dxf-viewer"
              LOCAL_PATH: "build"
              ACL: "public-read"

        artifacts:
          - build/*.tgz
